#!/usr/bin/env python3
"""
3D Molecule Ray-tracer: Generate cinematic-quality rendering scripts for PyMOL and ChimeraX.

Creates publication-ready molecular images with ray-tracing, depth of field, 
ambient occlusion, and cinematic lighting effects.

Usage:
    python main.py --software pymol --pdb 1mbn --preset cover [options]
    python main.py --software chimerax --pdb 1mbn --dof-focus "A:64" --output render.cxc
"""

import argparse
import sys
from pathlib import Path
from typing import List, Optional, Dict, Any


class RenderPreset:
    """Predefined rendering configurations."""
    
    PRESETS = {
        "standard": {
            "resolution": 2400,
            "dof": False,
            "dof_aperture": 0,
            "ao": False,
            "shadows": False,
            "fog": 0.0,
            "lighting": "default",
            "antialias": 2,
        },
        "cover": {
            "resolution": 3000,
            "dof": True,
            "dof_aperture": 2.0,
            "ao": True,
            "shadows": True,
            "fog": 0.1,
            "lighting": "cinematic",
            "antialias": 4,
        },
        "publication": {
            "resolution": 2400,
            "dof": False,
            "dof_aperture": 0,
            "ao": False,
            "shadows": False,
            "fog": 0.0,
            "lighting": "studio",
            "antialias": 2,
        },
        "cinematic": {
            "resolution": 3840,
            "dof": True,
            "dof_aperture": 3.0,
            "ao": True,
            "shadows": True,
            "fog": 0.3,
            "lighting": "cinematic",
            "antialias": 4,
        },
    }
    
    @classmethod
    def get(cls, name: str) -> Dict[str, Any]:
        """Get preset configuration."""
        if name not in cls.PRESETS:
            raise ValueError(f"Unknown preset: {name}. Available: {list(cls.PRESETS.keys())}")
        return cls.PRESETS[name].copy()


class PyMOLRenderer:
    """Generate PyMOL ray-tracing scripts with advanced effects."""
    
    LIGHTING_PRESETS = {
        "default": {
            "ambient": 0.2,
            "direct": 0.5,
            "specular": 0.5,
            "spec_power": 55,
        },
        "cinematic": {
            "ambient": 0.15,
            "direct": 0.6,
            "specular": 0.7,
            "spec_power": 80,
        },
        "studio": {
            "ambient": 0.4,
            "direct": 0.4,
            "specular": 0.3,
            "spec_power": 40,
        },
        "outdoor": {
            "ambient": 0.3,
            "direct": 0.7,
            "specular": 0.6,
            "spec_power": 60,
        },
    }
    
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        
    def generate_script(self) -> str:
        """Generate complete PyMOL script."""
        lines = []
        
        # Header
        lines.extend(self._generate_header())
        
        # Load structure
        lines.extend(self._generate_load())
        
        # Basic settings
        lines.extend(self._generate_settings())
        
        # Representation
        lines.extend(self._generate_representation())
        
        # Lighting
        lines.extend(self._generate_lighting())
        
        # Effects (AO, shadows, fog)
        lines.extend(self._generate_effects())
        
        # Depth of Field
        lines.extend(self._generate_dof())
        
        # Camera and view
        lines.extend(self._generate_camera())
        
        # Ray tracing
        lines.extend(self._generate_raytrace())
        
        return "\n".join(lines)
    
    def _generate_header(self) -> List[str]:
        """Generate script header."""
        return [
            "# PyMOL Ray-Traced Rendering Script",
            "# Generated by 3D Molecule Ray-tracer",
            f"# Target: {self.config['pdb']}",
            f"# Preset: {self.config['preset']}",
            "",
            "from pymol import cmd",
            "",
        ]
    
    def _generate_load(self) -> List[str]:
        """Generate structure loading commands."""
        pdb = self.config['pdb']
        lines = ["# Load structure"]
        
        # Check if PDB ID or file path
        if len(pdb) == 4 and pdb.isalnum() and not Path(pdb).exists():
            lines.append(f"fetch {pdb}, async=0")
        else:
            lines.append(f"load {pdb}")
        
        lines.append("")
        return lines
    
    def _generate_settings(self) -> List[str]:
        """Generate basic display settings."""
        bg_color = self.config.get('bg_color', 'white')
        antialias = self.config.get('antialias', 2)
        
        return [
            "# Basic settings",
            f"bg_color {bg_color}",
            f"set antialias, {antialias}",
            "set orthoscopic, 1",
            "set valence, 0",
            "",
        ]
    
    def _generate_representation(self) -> List[str]:
        """Generate representation commands."""
        style = self.config.get('style', 'cartoon')
        
        lines = ["# Representation settings", "hide everything"]
        
        if style == "surface":
            lines.extend([
                "show surface",
                "set surface_quality, 2",
                "set solvent_radius, 1.4",
            ])
        elif style == "ribbon":
            lines.extend([
                "show ribbon",
                "set ribbon_width, 4",
                "set ribbon_smooth, 1",
            ])
        elif style == "spheres":
            lines.extend([
                "show spheres",
                "set sphere_quality, 3",
            ])
        else:  # cartoon
            lines.extend([
                "show cartoon",
                "set cartoon_fancy_helices, 1",
                "set cartoon_fancy_sheets, 1",
                "set cartoon_smooth_loops, 1",
                "set cartoon_side_chain_helper, 1",
            ])
        
        # Color scheme
        lines.extend([
            "",
            "# Color scheme",
            "util.cbc()  # Color by chain",
            "",
        ])
        
        return lines
    
    def _generate_lighting(self) -> List[str]:
        """Generate lighting configuration."""
        lighting = self.config.get('lighting', 'default')
        preset = self.LIGHTING_PRESETS.get(lighting, self.LIGHTING_PRESETS['default'])
        
        lines = [
            "# Lighting configuration",
            f"set ambient, {preset['ambient']}",
            f"set direct, {preset['direct']}",
            f"set reflect, {preset['specular']}",
            f"set spec_power, {preset['spec_power']}",
        ]
        
        if lighting == "cinematic":
            lines.extend([
                "",
                "# Three-point lighting setup",
                "set light_count, 3",
                "set light1, [0.5, 0.5, -1.0]  # Key light",
                "set light2, [-0.8, 0.3, -0.5]  # Fill light",
                "set light3, [0.2, -0.9, -0.3]  # Rim light",
            ])
        
        lines.append("")
        return lines
    
    def _generate_effects(self) -> List[str]:
        """Generate ambient occlusion and shadow settings."""
        lines = ["# Advanced effects"]
        
        # Ambient occlusion
        if self.config.get('ao', False):
            lines.extend([
                "# Ambient occlusion",
                "set ambient_occlusion_mode, 1",
                "set ambient_occlusion_scale, 1.0",
                "set ambient_occlusion_smooth, 1",
            ])
        
        # Shadows
        if self.config.get('shadows', False):
            lines.extend([
                "# Soft shadows",
                "set ray_shadows, 1",
                "set ray_shadow_fudge, 0.1",
            ])
        else:
            lines.append("set ray_shadows, 0")
        
        # Fog/Depth cueing
        fog = self.config.get('fog', 0.0)
        if fog > 0:
            lines.extend([
                f"# Volumetric fog (depth cueing)",
                f"set depth_cue, 1",
                f"set fog, {fog}",
                f"set fog_start, 0.5",
            ])
        else:
            lines.extend([
                "set depth_cue, 0",
                "set fog, 0",
            ])
        
        lines.append("")
        return lines
    
    def _generate_dof(self) -> List[str]:
        """Generate depth of field configuration."""
        lines = ["# Depth of Field settings"]
        
        if self.config.get('dof', False):
            dof_focus = self.config.get('dof_focus', 'center')
            dof_aperture = self.config.get('dof_aperture', 2.0)
            
            lines.extend([
                f"set ray_trace_mode, 1",
                f"set ray_trace_gain, {0.005 * dof_aperture:.4f}",
                f"set dof_mode, 1",
                f"set dof_aperture, {dof_aperture}",
            ])
            
            if dof_focus == "center":
                lines.extend([
                    "center",
                    f"set dof_focus, 0  # Focus on center",
                ])
            elif dof_focus == "selection":
                lines.extend([
                    "# Focus on current selection (set sele before running)",
                    "center sele",
                    "set dof_focus, 0",
                ])
            else:
                # Specific residue
                lines.extend([
                    f"# Focus on {dof_focus}",
                    f"select dof_target, {dof_focus}",
                    "center dof_target",
                    "set dof_focus, 0",
                ])
        else:
            lines.extend([
                "set dof_mode, 0  # DOF disabled",
                "set ray_trace_mode, 1",
                "set ray_trace_gain, 0.01",
            ])
        
        lines.append("")
        return lines
    
    def _generate_camera(self) -> List[str]:
        """Generate camera positioning."""
        return [
            "# Camera setup",
            "reset",
            "zoom complete=1",
            "",
        ]
    
    def _generate_raytrace(self) -> List[str]:
        """Generate ray tracing and output commands."""
        resolution = self.config.get('resolution', 2400)
        output = self.config.get('output', 'output.png')
        
        # Change extension to .png if not already
        if not output.endswith('.png'):
            output = output.replace('.pml', '.png')
        
        return [
            "# Ray tracing and output",
            f"set ray_trace_fog, 1",
            f"set ray_trace_frames, 0",
            f"ray {resolution}, {resolution}",
            f"png {output}, dpi=300",
            "",
            f'print("Rendering complete: {output}")',
            "",
        ]


class ChimeraXRenderer:
    """Generate UCSF ChimeraX rendering scripts."""
    
    LIGHTING_PRESETS = {
        "default": "simple",
        "cinematic": "three-point",
        "studio": "soft",
        "outdoor": "outdoor",
    }
    
    def __init__(self, config: Dict[str, Any]):
        self.config = config
    
    def generate_script(self) -> str:
        """Generate complete ChimeraX script."""
        lines = []
        
        # Header
        lines.extend(self._generate_header())
        
        # Load structure
        lines.extend(self._generate_load())
        
        # Representation
        lines.extend(self._generate_representation())
        
        # Lighting and effects
        lines.extend(self._generate_lighting())
        
        # Camera
        lines.extend(self._generate_camera())
        
        # Render
        lines.extend(self._generate_render())
        
        return "\n".join(lines)
    
    def _generate_header(self) -> List[str]:
        """Generate script header."""
        return [
            "# UCSF ChimeraX Ray-Tracing Script",
            "# Generated by 3D Molecule Ray-tracer",
            f"# Target: {self.config['pdb']}",
            f"# Preset: {self.config['preset']}",
            "",
        ]
    
    def _generate_load(self) -> List[str]:
        """Generate structure loading commands."""
        pdb = self.config['pdb']
        lines = ["# Load structure"]
        
        if len(pdb) == 4 and pdb.isalnum() and not Path(pdb).exists():
            lines.append(f"open {pdb}")
        else:
            lines.append(f"open {pdb}")
        
        lines.append("")
        return lines
    
    def _generate_representation(self) -> List[str]:
        """Generate representation commands."""
        style = self.config.get('style', 'cartoon')
        
        lines = ["# Representation"]
        
        if style == "surface":
            lines.extend([
                "hide atoms",
                "show surfaces",
                "surface style solid",
            ])
        elif style == "ribbon":
            lines.extend([
                "hide atoms",
                "show ribbons",
            ])
        elif style == "spheres":
            lines.extend([
                "show atoms",
                "style atom sphere",
            ])
        else:  # cartoon
            lines.extend([
                "hide atoms",
                "show cartoons",
                "cartoon style protein modeh shape box",
            ])
        
        # Color
        lines.extend([
            "",
            "# Color by chain",
            "color bychain",
            "",
        ])
        
        return lines
    
    def _generate_lighting(self) -> List[str]:
        """Generate lighting and effects configuration."""
        lighting = self.config.get('lighting', 'default')
        preset = self.LIGHTING_PRESETS.get(lighting, 'simple')
        
        lines = [
            "# Lighting and effects",
            f"lighting {preset}",
        ]
        
        # Shadows
        if self.config.get('shadows', False):
            lines.append("lighting shadows true")
        else:
            lines.append("lighting shadows false")
        
        # Ambient occlusion
        if self.config.get('ao', False):
            lines.append("lighting ambientOcclusion true")
        else:
            lines.append("lighting ambientOcclusion false")
        
        # Depth of Field
        if self.config.get('dof', False):
            dof_aperture = self.config.get('dof_aperture', 2.0)
            lines.extend([
                f"camera dof true",
                f"camera dof_fNumber {dof_aperture:.1f}",
            ])
            
            dof_focus = self.config.get('dof_focus', 'center')
            if dof_focus == "center":
                lines.append("# Focus on center (default)")
            elif dof_focus != "selection":
                lines.extend([
                    f"# Focus on {dof_focus}",
                    f"select {dof_focus}",
                    "view selection",
                ])
        
        lines.append("")
        return lines
    
    def _generate_camera(self) -> List[str]:
        """Generate camera positioning."""
        return [
            "# Camera setup",
            "view orient",
            "zoom",
            "",
        ]
    
    def _generate_render(self) -> List[str]:
        """Generate render and save commands."""
        resolution = self.config.get('resolution', 2400)
        output = self.config.get('output', 'output.png')
        
        # Change extension if needed
        if output.endswith('.cxc'):
            output = output.replace('.cxc', '.png')
        
        bg_color = self.config.get('bg_color', 'white')
        
        return [
            "# Render settings",
            f"set bgColor {bg_color}",
            f"graphics rate maxFrameRate 60",
            "",
            "# Save high-quality image",
            f"save {output} supersample 3",
            "",
            f'echo "Rendering complete: {output}"',
            "",
        ]


def main():
    parser = argparse.ArgumentParser(
        description="Generate cinematic molecular rendering scripts for PyMOL and ChimeraX",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Cover-quality render with PyMOL
  python main.py --software pymol --pdb 1mbn --preset cover
  
  # Custom depth of field with ChimeraX
  python main.py --software chimerax --pdb 1abc --dof-focus "A:64" --dof-aperture 2.0
  
  # Publication-ready with specific style
  python main.py --software pymol --pdb protein.pdb --preset publication --style surface
  
  # Cinematic 4K render
  python main.py --software pymol --pdb 1mbn --preset cinematic --resolution 3840
        """
    )
    
    # Required arguments
    parser.add_argument("--software", choices=["pymol", "chimerax"], default="pymol",
                        help="Target rendering software (default: pymol)")
    parser.add_argument("--pdb", required=True,
                        help="PDB file path or 4-letter PDB ID")
    
    # Presets
    parser.add_argument("--preset", choices=["standard", "cover", "publication", "cinematic"],
                        default="standard",
                        help="Rendering preset (default: standard)")
    
    # Style options
    parser.add_argument("--style", choices=["cartoon", "surface", "ribbon", "spheres"],
                        default="cartoon",
                        help="Molecular representation style (default: cartoon)")
    parser.add_argument("--resolution", type=int, default=None,
                        help="Output resolution in pixels (overrides preset)")
    parser.add_argument("--bg-color", default="white",
                        help="Background color (default: white)")
    
    # Effects
    parser.add_argument("--ao-on", action="store_true",
                        help="Enable ambient occlusion")
    parser.add_argument("--shadows", action="store_true",
                        help="Enable shadow casting")
    parser.add_argument("--fog", type=float, default=None,
                        help="Fog density 0-1 (default: from preset)")
    
    # Depth of field
    parser.add_argument("--dof-on", action="store_true",
                        help="Enable depth of field")
    parser.add_argument("--dof-focus", default="center",
                        help="DOF focus: center, selection, or residue spec (e.g., 'A:64')")
    parser.add_argument("--dof-aperture", type=float, default=None,
                        help="Aperture size, higher = more blur (default: from preset)")
    
    # Lighting
    parser.add_argument("--lighting", choices=["default", "cinematic", "studio", "outdoor"],
                        default=None,
                        help="Lighting preset (default: from preset)")
    
    # Output
    parser.add_argument("--output", default=None,
                        help="Output script filename (default: auto-generated)")
    
    args = parser.parse_args()
    
    # Get preset configuration
    config = RenderPreset.get(args.preset)
    
    # Override with command-line arguments
    config['software'] = args.software
    config['pdb'] = args.pdb
    config['preset'] = args.preset
    config['style'] = args.style
    config['bg_color'] = args.bg_color
    config['dof_focus'] = args.dof_focus
    
    if args.resolution is not None:
        config['resolution'] = args.resolution
    if args.fog is not None:
        config['fog'] = args.fog
    if args.dof_aperture is not None:
        config['dof_aperture'] = args.dof_aperture
    if args.lighting is not None:
        config['lighting'] = args.lighting
    
    # Boolean flags override preset
    if args.ao_on:
        config['ao'] = True
    if args.shadows:
        config['shadows'] = True
    if args.dof_on:
        config['dof'] = True
    
    # Generate output filename
    if args.output is None:
        ext = ".pml" if args.software == "pymol" else ".cxc"
        args.output = f"{args.preset}_render{ext}"
    config['output'] = args.output
    
    # Generate script
    try:
        if args.software == "pymol":
            renderer = PyMOLRenderer(config)
        else:
            renderer = ChimeraXRenderer(config)
        
        script = renderer.generate_script()
        
        # Save script
        output_path = Path(args.output)
        output_path.write_text(script)
        
        print(f"✓ Rendering script generated: {output_path.absolute()}")
        print(f"\nConfiguration:")
        print(f"  Software: {args.software}")
        print(f"  Preset: {args.preset}")
        print(f"  Style: {args.style}")
        print(f"  Resolution: {config['resolution']}px")
        print(f"  Depth of Field: {'ON' if config['dof'] else 'OFF'}")
        print(f"  Ambient Occlusion: {'ON' if config['ao'] else 'OFF'}")
        print(f"  Shadows: {'ON' if config['shadows'] else 'OFF'}")
        print(f"  Lighting: {config['lighting']}")
        print(f"\nTo render:")
        if args.software == "pymol":
            print(f"  pymol {args.output}")
            print(f"  # Or within PyMOL:")
            print(f"  @ {args.output}")
        else:
            print(f"  chimerax {args.output}")
            
    except Exception as e:
        print(f"Error generating script: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
