#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description='Render markdown summary report for Auto-Proteomics DDA workflow')
    p.add_argument('--matrix', required=True)
    p.add_argument('--metadata', required=True)
    p.add_argument('--diff-all', required=True)
    p.add_argument('--diff-significant', required=True)
    p.add_argument('--report', required=True)
    p.add_argument('--summary-json', required=True)
    return p.parse_args()


def count_rows(path: str) -> int:
    with open(path, 'r', encoding='utf-8', newline='') as fh:
        reader = csv.reader(fh, delimiter='\t')
        next(reader, None)
        return sum(1 for _ in reader)


def main() -> int:
    args = parse_args()
    with open(args.metadata, 'r', encoding='utf-8', newline='') as fh:
        metadata = list(csv.DictReader(fh, delimiter='\t'))
    with open(args.diff_all, 'r', encoding='utf-8', newline='') as fh:
        diff_all = list(csv.DictReader(fh, delimiter='\t'))
    with open(args.diff_significant, 'r', encoding='utf-8', newline='') as fh:
        diff_sig = list(csv.DictReader(fh, delimiter='\t'))
    conditions = {}
    for row in metadata:
        conditions[row['condition']] = conditions.get(row['condition'], 0) + 1
    up = sum(1 for r in diff_all if r.get('direction') == 'up')
    down = sum(1 for r in diff_all if r.get('direction') == 'down')
    summary = {
        'samples': len(metadata),
        'conditions': conditions,
        'proteins_after_filter': count_rows(args.matrix),
        'significant_proteins': len(diff_sig),
        'up': up,
        'down': down,
    }
    lines = [
        '# Auto-Proteomics Report',
        '',
        '## Summary',
        f"- Samples: {summary['samples']}",
        f"- Conditions: {conditions}",
        f"- Proteins after filtering: {summary['proteins_after_filter']}",
        f"- Significant proteins: {summary['significant_proteins']}",
        f"- Up-regulated: {summary['up']}",
        f"- Down-regulated: {summary['down']}",
        '',
        '## Notes',
        '- This report is generated by the current release-track DDA LFQ downstream workflow for Auto-Proteomics.',
        '- The current implementation assumes processed MaxQuant-like protein-level inputs.',
    ]
    Path(args.report).write_text('\n'.join(lines) + '\n', encoding='utf-8')
    Path(args.summary_json).write_text(json.dumps(summary, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
