#!/usr/bin/env python3
"""
Performance Monitor / 性能监控器
Auto-generated by Self-Evolution System
"""

import time
import json
from datetime import datetime
from typing import Dict, Any

class PerformanceMonitor:
    """监控技能性能"""
    
    def __init__(self):
        self.metrics = []
    
    def record(self, operation: str, duration: float, success: bool):
        """记录操作性能"""
        self.metrics.append({
            "timestamp": datetime.now().isoformat(),
            "operation": operation,
            "duration_ms": duration * 1000,
            "success": success
        })
    
    def get_stats(self) -> Dict[str, Any]:
        """获取统计信息"""
        if not self.metrics:
            return {}
        
        durations = [m["duration_ms"] for m in self.metrics]
        return {
            "total_operations": len(self.metrics),
            "avg_duration_ms": sum(durations) / len(durations),
            "max_duration_ms": max(durations),
            "min_duration_ms": min(durations),
            "success_rate": sum(1 for m in self.metrics if m["success"]) / len(self.metrics)
        }
